apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
spec:
  selector:
    matchLabels:
      run: frontend-web
  replicas: 2
  template:
    metadata:
      labels:
        run: frontend-web
    spec:
      containers:
      - name: frontend-web
        image: learndockerwithme/kubernates-project-1
        ports:
        - containerPort: 8080
